version: '2'
services:
  redis:
    image: "redis:alpine"
    networks:
      - nekoyume-net
  nekoyume:
    image: "nekoyume:latest"
    environment:
      - REDIS_URL=redis://redis:6379/
    ports:
      - "4000:80"
    depends_on:
      - redis
    networks:
      - nekoyume-net
networks:
  nekoyume-net:
