version: '3'
services:
  redis:
    image: redis:alpine
    networks: [nekoyume-net]
  postgres:
    image: postgres:alpine
    networks: [nekoyume-net]
    environment:
      POSTGRES_PASSWORD: nekoyume
      POSTGRES_DB: nekoyume
  sync: &app
    build: .
    image: nekoyume/nekoyume
    command:
    -
      nekoyume init --skip-sync &&
      nekoyume sync
    environment: &app_environments
      CACHE_TYPE: redis
      DATABASE_URL: postgresql://postgres:nekoyume@postgres/nekoyume
      CELERY_BROKER_URL: redis://redis:6379
      CELERY_RESULT_BACKEND: redis://redis:6379
      REDIS_URL: redis://redis:6379
      SEED_NODE_URL: http://web:8080
    depends_on: [postgres, redis]
    networks: [nekoyume-net]
  web:
    <<: *app
    command:
    -
      nekoyume init --skip-sync &&
      gunicorn
        -b 0.0.0.0:8080
        -w 3
        -k gevent
        --log-level debug
        --reload
        nekoyume.app:app;
    volumes:
    - '.:/app'
    depends_on: [sync]
    ports:
    - "4000:8080"
    restart: always
  worker:
    <<: *app
    command:
    -
      nekoyume init --skip-sync &&
      celery
        -A nekoyume.app.cel
        worker
          -l info;
    depends_on: [sync]
    environment:
      <<: *app_environments
      C_FORCE_ROOT: "true"
  miner:
    <<: *app
    command:
      -
        nekoyume init --skip-sync &&
        nekoyume mine ${MINER_KEY}
    depends_on: [sync]
networks:
  nekoyume-net:
