version: '2'
services:
  redis:
    image: "redis:alpine"
    networks:
      - nekoyume-net
  nekoyume:
    build: .
    image: "nekoyume/nekoyume"
    environment:
      - REDIS_URL=redis://redis:6379
      - C_FORCE_ROOT=true
    ports:
      - "4000:8080"
    depends_on:
      - redis
    networks:
      - nekoyume-net
networks:
  nekoyume-net:
